### ISSUE TITLE
Hardware para VLSI

### ISSUE THREAD

**Issue by jorgelmp** [aMurryFly/CompuGrafica-VLSI#1]
¡Hola, compañero! 

Primero que nada me gustaría agradecerte por tus repositorios semestrales. Me han ayudado mucho para saber qué esperar de los profesores. 
Estoy haciendo mi horario para el séptimo semestre. Para mi clase de Diseño Digital Moderno compré la FPGA Cyclone IV, pues la profesora Norma Chavez nos dio la opción. ¿Sabes si la profesora Elizabeth Fonseca de VLSI sólo trabaja con la DE10-Lite o también con otras tarjetas?

**Comment by aMurryFly** [comment]
La profesora Fonseca solo usa DE10-lite, realmente creo que puede darte la flexibilidad de usar lo que quieras pero no te sugiero eso sobre todo por cómo da el curso
